### ISSUE TITLE
Add ocplib-json-typed

### ISSUE THREAD

**Issue by gpetiot** [dune-universe/opam-overlays#108]
The package `ocplib-json-typed` (https://github.com/OCamlPro/ocplib-json-typed) doesn't have a dune file, and it's a dependency of ocp-indent (that we use as a lib in ocamlformat), is it possible to add it on this repo? Thanks!

**Comment by NathanReb** [comment]
The missing dune-project can cause build failures when vendored indeed. Submitting a patch upstream would be best but if you need an older version patched in the meantime we can probably host it here!

**Comment by Leonidas-from-XIV** [comment]
Ah, it already exists: https://github.com/OCamlPro/ocplib-json-typed/pull/37
