### ISSUE TITLE
io-page 2.3 port needs investigation

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [dune-universe/opam-overlays#142]
Our current port of io-page 2.3 has a number of issues:

1. Uses a git link as the source, which while not technically a problem is currently discouraged
2. The git link does not point to our fork
3. The git link points to the default git branch, thus us claiming that this is io-page 2.3 is wrong, especially given 2.4 was released
4. io-page 2.3 and 2.4 seem to use dune upstream, so it needs investigation what our port adds.

**Comment by TheLortex** [comment]
It was useful when `io-page 2.3` was not released as a way to test the dune port of `io-page`, but now that 2.3 and 2.4 are released, I think the port can be removed. 
.

**Comment by Leonidas-from-XIV** [comment]
Thanks for that info, that might explain the issue.

I don't think we can remove the port because it will break everyone who locked on it. However I would suggest to change the URL to point to the `v2.3.0` tag and maybe add an `avoid-version` tag so opam-monorepo (after [#269](https://github.com/ocamllabs/opam-monorepo/pull/269) is merged) will avoid this version and pick 2.3.0 from opam-repository instead.
