### ISSUE TITLE
Mtime overlay doesn't provide `mtime.clock`

### ISSUE THREAD

**Issue by CraigFe** [dune-universe/opam-overlays#84]
`mtime` provides a `mtime.clock` ocamlfind library from version 1.0 onwards. I believe this library is empty and exists only to namespace `mtime.clock.{os,jsoo}` (see [META](https://github.com/dbuenzli/mtime/blob/master/pkg/META#L19)) but the fact that we don't provide it is a breaking change regardless.

Reporting this issue here since issues are disabled for `dune-universe/mtime`.

**Comment by CraigFe** [comment]
Patch fixing this issue here: https://github.com/CraigFe/mtime/tree/duniverse-v1.2.1

**Comment by TheLortex** [comment]
Thank you, the patch has been integrated in `mtime.1.3.0` (https://github.com/dune-universe/opam-overlays/pull/117)
