### ISSUE TITLE
update topkg

### ISSUE THREAD

**Issue by hannesm** [dune-universe/opam-overlays#93]
to released version 1.0.4

**Comment by NathanReb** [comment]
Do you have a concrete example where you need `topkg` in your monorepo? No package in opam (upstream and opam-overlays) depends on both topkg and dune so it seems that opam-monorepo would never lock `topkg`.

I might definitely be missing something here but in most cases `topkg` is used as an alternative to dune so I don't think there would be a reason to port it to dune for opam-monorepo. It's likely a mistake that it was ported initally.

**Comment by hannesm** [comment]
> It's likely a mistake that it was ported initally.

maybe. I opened this issue when checking which packages were used by my dependency cone. Now that I think about it, indeed having topkg in this overlay doesn't make much sense.
